export const HOME = "/"
export const CATALOG = "/catalog"
export const LOGIN = "/login"
export const SIGNUP = "/signup"
export const UPLOAD = "/upload"
export const ALBUM = "/albums/:albumId"
export const PROFILE = "/profile/:username"
export const COLLECTION = "/collection/:username"
export const WISHLIST = "/wishlist/:username"
export const MY_UPLOADS = "/my-uploads/:username"

export const SEARCH = "/search"
export const SEARCH_RESULTS = "/search/search-results/:searchQuery"
export const NOT_FOUND = ""
